main:
  - name: Mesh Map
    identifier: meshmap
    url: https://map.areyoumeshingwith.us
    weight: 80
    params:
      icon:
        header: Florida Mesh Map
        vendor: font-awesome-solid
        name: map-location-dot

  - name: Malla
    parent: telemetry
    url: https://malla.areyoumeshingwith.us/
    weight: 73
    params:
      icon:
        header: Malla
        vendor: font-awesome-solid
        name: gauge
        color: green

    
  - name: Meshview
    parent: telemetry
    url: https://meshview.areyoumeshingwith.us/
    weight: 74
    params:
      icon:
        header: Meshview
        vendor: font-awesome-solid
        name: gauge
        color: green